export const dummyLiabilities = [
  {
    id: "LIA-1001",
    receivedDate: "2026-08-15",
    head: "Office Expense",
    subHead: "Rent",
    source: "Cash",
    voucherNo: "VOUCH-8801",
    amount: 15000,
    notes: "Monthly office space rent for August 2026.",
  },
  {
    id: "LIA-1002",
    receivedDate: "2026-08-18",
    head: "Office Expense",
    subHead: "Utility",
    source: "Bank",
    voucherNo: "VOUCH-8802",
    amount: 3200,
    notes: "Electricity and Internet bill payment.",
  },
  {
    id: "LIA-1003",
    receivedDate: "2026-08-19",
    head: "Office Expense",
    subHead: "Utility",
    source: "Service",
    voucherNo: "VOUCH-8803",
    amount: 1200,
    notes: "Water supply bill.",
  },
  {
    id: "LIA-1004",
    receivedDate: "2026-08-20",
    head: "Materials",
    subHead: "Crown",
    source: "Supplier",
    voucherNo: "VOUCH-8804",
    amount: 8500,
    notes: "Supplier due payment for dental crowns.",
  },
  {
    id: "LIA-1005",
    receivedDate: "2026-08-21",
    head: "Materials",
    subHead: "Crown",
    source: "Service",
    voucherNo: "VOUCH-8805",
    amount: 4200,
    notes: "Crown lab polish service bill.",
  },
  {
    id: "LIA-1006",
    receivedDate: "2026-08-22",
    head: "Sales & Marketing",
    subHead: "Advertising",
    source: "Service",
    voucherNo: "VOUCH-8806",
    amount: 5000,
    notes: "Facebook campaign ad bill for August.",
  },
  {
    id: "LIA-1007",
    receivedDate: "2026-08-23",
    head: "Sales & Marketing",
    subHead: "Transportation",
    source: "Cash",
    voucherNo: "VOUCH-8807",
    amount: 1800,
    notes: "Marketing team local conveyance expenses.",
  },
  {
    id: "LIA-1008",
    receivedDate: "2026-08-25",
    head: "Employee",
    subHead: "Salary",
    source: "Bank",
    voucherNo: "VOUCH-8808",
    amount: 25000,
    notes: "Staff salary clearance.",
  },
  {
    id: "LIA-1009",
    receivedDate: "2026-08-26",
    head: "Employee",
    subHead: "Entertainment",
    source: "Cash",
    voucherNo: "VOUCH-8809",
    amount: 1500,
    notes: "Staff weekend snacks allowance.",
  },
  {
    id: "LIA-1010",
    receivedDate: "2026-08-28",
    head: "Other",
    subHead: "Maintenance",
    source: "Supplier",
    voucherNo: "VOUCH-8810",
    amount: 3500,
    notes: "AC repair and servicing charge.",
  },
];