export const styles = {
  container: {
    width: "100%",
    overflowX: "auto",
    margin: "20px 0",
    fontFamily: "Arial, sans-serif",
  },
  loading: {
    padding: "20px",
    textAlign: "center",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    textAlign: "center",
    backgroundColor: "#ffffff",
  },
  th: {
    border: "1px solid #000000",
    backgroundColor: "#e8e8e8",
    padding: "10px 12px",
    fontWeight: "normal",
    fontSize: "14px",
    lineHeight: "1.3",
    color: "#000000",
  },
  td: {
    border: "1px solid #000000",
    padding: "10px 12px",
    fontSize: "14px",
    verticalAlign: "middle",
  },
  actionBtn: {
    background: "none",
    border: "none",
    color: "#000000",
    textDecoration: "underline",
    fontWeight: "500",
    cursor: "pointer",
    fontSize: "14px",
  },
  modalOverlay: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.5)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1000,
  },
  modalContent: {
    backgroundColor: "#fff",
    padding: "20px",
    borderRadius: "6px",
    width: "400px",
    maxWidth: "90%",
  },
  modalHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottom: "1px solid #ddd",
    paddingBottom: "10px",
  },
  modalBody: {
    paddingTop: "15px",
  },
  modalImage: {
    width: "100%",
    borderRadius: "4px",
  },
  closeBtn: {
    background: "none",
    border: "none",
    fontSize: "22px",
    cursor: "pointer",
    lineHeight: "1",
  },
};