export const mockReportData = [
  {
    id: 1,
    paymentDate: "2026-03-03",
    deliveryDate: "2026-03-03",
    voucherId: "VOUCH-803",
    doctorId: "DOC-01",
    doctorName: "Dr. Rahim Ahmed",
    clinicId: "CLN-01",
    clinicName: "City Hospital",
    state: "Dhaka",
    address: "House 12, Road 5, Dhanmondi, Dhaka",
    caseNo: "CS-9901",
    patientName: "Karim Uddin",
    paymentMethod: "Nagad",
    transactionNo: "TRX-3344",
    status: "Pending",
    paidAmount: 35000,
  },
  {
    id: 2,
    paymentDate: "2026-03-05",
    deliveryDate: "2026-03-05",
    voucherId: "VOUCH-805",
    doctorId: "DOC-01",
    doctorName: "Dr. Rahim Ahmed",
    clinicId: "CLN-01",
    clinicName: "City Hospital",
    state: "Dhaka",
    address: "House 12, Road 5, Dhanmondi, Dhaka",
    caseNo: "CS-9905",
    patientName: "Sumi Akter",
    paymentMethod: "Bkash",
    transactionNo: "TRX-5566",
    status: "Delivered",
    paidAmount: 50000,
  },
  {
    id: 3,
    paymentDate: "2026-03-12",
    deliveryDate: "2026-03-12",
    voucherId: "VOUCH-814",
    doctorId: "DOC-02",
    doctorName: "Dr. Sharmin Akter",
    clinicId: "CLN-02",
    clinicName: "Popular Diagnostic",
    state: "Chittagong",
    address: "GEC Circle, Chittagong",
    caseNo: "CS-9914",
    patientName: "Rafiqul Islam",
    paymentMethod: "Bank Transfer",
    transactionNo: "TRX-8812",
    status: "Received",
    paidAmount: 18000,
  },
  {
    id: 4,
    paymentDate: "2026-03-15",
    deliveryDate: "2026-03-15",
    voucherId: "VOUCH-820",
    doctorId: "DOC-02",
    doctorName: "Dr. Sharmin Akter",
    clinicId: "CLN-02",
    clinicName: "Popular Diagnostic",
    state: "Chittagong",
    address: "GEC Circle, Chittagong",
    caseNo: "CS-9920",
    patientName: "Jamal Hossain",
    paymentMethod: "Bkash",
    transactionNo: "TRX-2001",
    status: "Delivered",
    paidAmount: 18000,
  },
  {
    id: 5,
    paymentDate: "2026-01-10",
    deliveryDate: "2026-01-10",
    voucherId: "VOUCH-821",
    doctorId: "DOC-03",
    doctorName: "Dr. Tanvir Hassan",
    clinicId: "CLN-03",
    clinicName: "Labaid Specialized",
    state: "Dhaka",
    address: "Green Road, Dhanmondi, Dhaka",
    caseNo: "CS-9921",
    patientName: "Nusrat Jahan",
    paymentMethod: "Bkash",
    transactionNo: "TRX-1092",
    status: "Delivered",
    paidAmount: 22000,
  },
  {
    id: 6,
    paymentDate: "2026-01-14",
    deliveryDate: "2026-01-14",
    voucherId: "VOUCH-822",
    doctorId: "DOC-03",
    doctorName: "Dr. Tanvir Hassan",
    clinicId: "CLN-03",
    clinicName: "Labaid Specialized",
    state: "Dhaka",
    address: "Green Road, Dhanmondi, Dhaka",
    caseNo: "CS-9922",
    patientName: "Abul Kalam",
    paymentMethod: "Nagad",
    transactionNo: "TRX-4411",
    status: "Pending",
    paidAmount: 15000,
  },
  {
    id: 7,
    paymentDate: "2026-01-20",
    deliveryDate: "2026-01-20",
    voucherId: "VOUCH-823",
    doctorId: "DOC-04",
    doctorName: "Dr. Farhana Yasmin",
    clinicId: "CLN-04",
    clinicName: "Square Hospital",
    state: "Dhaka",
    address: "Panthapath, Dhaka",
    caseNo: "CS-9923",
    patientName: "Selim Reza",
    paymentMethod: "Bank Transfer",
    transactionNo: "TRX-9900",
    status: "Received",
    paidAmount: 45000,
  },
  {
    id: 8,
    paymentDate: "2026-01-25",
    deliveryDate: "2026-01-25",
    voucherId: "VOUCH-824",
    doctorId: "DOC-04",
    doctorName: "Dr. Farhana Yasmin",
    clinicId: "CLN-04",
    clinicName: "Square Hospital",
    state: "Dhaka",
    address: "Panthapath, Dhaka",
    caseNo: "CS-9924",
    patientName: "Mehedi Hasan",
    paymentMethod: "Bkash",
    transactionNo: "TRX-3011",
    status: "Delivered",
    paidAmount: 30000,
  },
  {
    id: 9,
    paymentDate: "2026-02-01",
    deliveryDate: "2026-02-01",
    voucherId: "VOUCH-825",
    doctorId: "DOC-05",
    doctorName: "Dr. Mahmudur Rahman",
    clinicId: "CLN-05",
    clinicName: "Ibn Sina Hospital",
    state: "Sylhet",
    address: "Subhanani, Sylhet",
    caseNo: "CS-9925",
    patientName: "Anisur Rahman",
    paymentMethod: "Nagad",
    transactionNo: "TRX-7722",
    status: "Pending",
    paidAmount: 27000,
  },
  {
    id: 10,
    paymentDate: "2026-02-03",
    deliveryDate: "2026-02-03",
    voucherId: "VOUCH-826",
    doctorId: "DOC-05",
    doctorName: "Dr. Mahmudur Rahman",
    clinicId: "CLN-05",
    clinicName: "Ibn Sina Hospital",
    state: "Sylhet",
    address: "Subhanani, Sylhet",
    caseNo: "CS-9926",
    patientName: "Tania Sultana",
    paymentMethod: "Bkash",
    transactionNo: "TRX-6610",
    status: "Delivered",
    paidAmount: 19500,
  },
  {
    id: 11,
    paymentDate: "2026-02-10",
    deliveryDate: "2026-02-10",
    voucherId: "VOUCH-827",
    doctorId: "DOC-06",
    doctorName: "Dr. Nabila Chowdhury",
    clinicId: "CLN-06",
    clinicName: "Mount Adora Hospital",
    state: "Sylhet",
    address: "Nayasarak, Sylhet",
    caseNo: "CS-9927",
    patientName: "Imran Hossain",
    paymentMethod: "Bank Transfer",
    transactionNo: "TRX-5533",
    status: "Received",
    paidAmount: 38000,
  },
  {
    id: 12,
    paymentDate: "2026-02-14",
    deliveryDate: "2026-02-14",
    voucherId: "VOUCH-828",
    doctorId: "DOC-06",
    doctorName: "Dr. Nabila Chowdhury",
    clinicId: "CLN-06",
    clinicName: "Mount Adora Hospital",
    state: "Sylhet",
    address: "Nayasarak, Sylhet",
    caseNo: "CS-9928",
    patientName: "Rupa Begum",
    paymentMethod: "Bkash",
    transactionNo: "TRX-8821",
    status: "Delivered",
    paidAmount: 12500,
  },
  {
    id: 13,
    paymentDate: "2026-02-18",
    deliveryDate: "2026-02-18",
    voucherId: "VOUCH-829",
    doctorId: "DOC-07",
    doctorName: "Dr. Kamrul Islam",
    clinicId: "CLN-07",
    clinicName: "Islami Bank Hospital",
    state: "Rajshahi",
    address: "Laxmipur, Rajshahi",
    caseNo: "CS-9929",
    patientName: "Sojib Ali",
    paymentMethod: "Nagad",
    transactionNo: "TRX-1122",
    status: "Pending",
    paidAmount: 25000,
  },
  {
    id: 14,
    paymentDate: "2026-02-22",
    deliveryDate: "2026-02-22",
    voucherId: "VOUCH-830",
    doctorId: "DOC-07",
    doctorName: "Dr. Kamrul Islam",
    clinicId: "CLN-07",
    clinicName: "Islami Bank Hospital",
    state: "Rajshahi",
    address: "Laxmipur, Rajshahi",
    caseNo: "CS-9930",
    patientName: "Shirin Akter",
    paymentMethod: "Bkash",
    transactionNo: "TRX-3399",
    status: "Delivered",
    paidAmount: 42000,
  },
  {
    id: 15,
    paymentDate: "2026-02-28",
    deliveryDate: "2026-02-28",
    voucherId: "VOUCH-831",
    doctorId: "DOC-08",
    doctorName: "Dr. Mizanur Rahman",
    clinicId: "CLN-08",
    clinicName: "Zamzam Hospital",
    state: "Rajshahi",
    address: "Greater Road, Rajshahi",
    caseNo: "CS-9931",
    patientName: "Kibriya Ahmed",
    paymentMethod: "Bank Transfer",
    transactionNo: "TRX-7711",
    status: "Received",
    paidAmount: 31000,
  },
  {
    id: 16,
    paymentDate: "2026-03-01",
    deliveryDate: "2026-03-01",
    voucherId: "VOUCH-832",
    doctorId: "DOC-01",
    doctorName: "Dr. Rahim Ahmed",
    clinicId: "CLN-01",
    clinicName: "City Hospital",
    state: "Dhaka",
    address: "House 12, Road 5, Dhanmondi, Dhaka",
    caseNo: "CS-9932",
    patientName: "Firoz Khan",
    paymentMethod: "Bkash",
    transactionNo: "TRX-4040",
    status: "Delivered",
    paidAmount: 16000,
  },
  {
    id: 17,
    paymentDate: "2026-03-02",
    deliveryDate: "2026-03-02",
    voucherId: "VOUCH-833",
    doctorId: "DOC-02",
    doctorName: "Dr. Sharmin Akter",
    clinicId: "CLN-02",
    clinicName: "Popular Diagnostic",
    state: "Chittagong",
    address: "GEC Circle, Chittagong",
    caseNo: "CS-9933",
    patientName: "Nasrin Sultana",
    paymentMethod: "Nagad",
    transactionNo: "TRX-5050",
    status: "Pending",
    paidAmount: 29000,
  },
  {
    id: 18,
    paymentDate: "2026-03-04",
    deliveryDate: "2026-03-04",
    voucherId: "VOUCH-834",
    doctorId: "DOC-09",
    doctorName: "Dr. Asif Mahmud",
    clinicId: "CLN-09",
    clinicName: "Parkview Hospital",
    state: "Chittagong",
    address: "Panchlaish, Chittagong",
    caseNo: "CS-9934",
    patientName: "Habibur Rahman",
    paymentMethod: "Bkash",
    transactionNo: "TRX-6060",
    status: "Delivered",
    paidAmount: 33000,
  },
  {
    id: 19,
    paymentDate: "2026-03-06",
    deliveryDate: "2026-03-06",
    voucherId: "VOUCH-835",
    doctorId: "DOC-09",
    doctorName: "Dr. Asif Mahmud",
    clinicId: "CLN-09",
    clinicName: "Parkview Hospital",
    state: "Chittagong",
    address: "Panchlaish, Chittagong",
    caseNo: "CS-9935",
    patientName: "Shahida Parveen",
    paymentMethod: "Bank Transfer",
    transactionNo: "TRX-7070",
    status: "Received",
    paidAmount: 21000,
  },
  {
    id: 20,
    paymentDate: "2026-03-08",
    deliveryDate: "2026-03-08",
    voucherId: "VOUCH-836",
    doctorId: "DOC-10",
    doctorName: "Dr. Shahriar Alam",
    clinicId: "CLN-10",
    clinicName: "Khulna City Medical",
    state: "Khulna",
    address: "KDA Avenue, Khulna",
    caseNo: "CS-9936",
    patientName: "Mostafa Jamal",
    paymentMethod: "Bkash",
    transactionNo: "TRX-8080",
    status: "Delivered",
    paidAmount: 48000,
  },
  {
    id: 21,
    paymentDate: "2026-03-10",
    deliveryDate: "2026-03-10",
    voucherId: "VOUCH-837",
    doctorId: "DOC-10",
    doctorName: "Dr. Shahriar Alam",
    clinicId: "CLN-10",
    clinicName: "Khulna City Medical",
    state: "Khulna",
    address: "KDA Avenue, Khulna",
    caseNo: "CS-9937",
    patientName: "Laila Arjumand",
    paymentMethod: "Nagad",
    transactionNo: "TRX-9090",
    status: "Pending",
    paidAmount: 17500,
  },
  {
    id: 22,
    paymentDate: "2026-03-11",
    deliveryDate: "2026-03-11",
    voucherId: "VOUCH-838",
    doctorId: "DOC-03",
    doctorName: "Dr. Tanvir Hassan",
    clinicId: "CLN-03",
    clinicName: "Labaid Specialized",
    state: "Dhaka",
    address: "Green Road, Dhanmondi, Dhaka",
    caseNo: "CS-9938",
    patientName: "Zahid Hasan",
    paymentMethod: "Bkash",
    transactionNo: "TRX-1010",
    status: "Delivered",
    paidAmount: 39000,
  },
  {
    id: 23,
    paymentDate: "2026-03-13",
    deliveryDate: "2026-03-13",
    voucherId: "VOUCH-839",
    doctorId: "DOC-04",
    doctorName: "Dr. Farhana Yasmin",
    clinicId: "CLN-04",
    clinicName: "Square Hospital",
    state: "Dhaka",
    address: "Panthapath, Dhaka",
    caseNo: "CS-9939",
    patientName: "Monirul Islam",
    paymentMethod: "Bank Transfer",
    transactionNo: "TRX-2020",
    status: "Received",
    paidAmount: 55000,
  },
  {
    id: 24,
    paymentDate: "2026-03-14",
    deliveryDate: "2026-03-14",
    voucherId: "VOUCH-840",
    doctorId: "DOC-05",
    doctorName: "Dr. Mahmudur Rahman",
    clinicId: "CLN-05",
    clinicName: "Ibn Sina Hospital",
    state: "Sylhet",
    address: "Subhanani, Sylhet",
    caseNo: "CS-9940",
    patientName: "Farzana Parveen",
    paymentMethod: "Bkash",
    transactionNo: "TRX-3030",
    status: "Delivered",
    paidAmount: 26000,
  },
  {
    id: 25,
    paymentDate: "2026-03-16",
    deliveryDate: "2026-03-16",
    voucherId: "VOUCH-841",
    doctorId: "DOC-06",
    doctorName: "Dr. Nabila Chowdhury",
    clinicId: "CLN-06",
    clinicName: "Mount Adora Hospital",
    state: "Sylhet",
    address: "Nayasarak, Sylhet",
    caseNo: "CS-9941",
    patientName: "Bashir Ahmed",
    paymentMethod: "Nagad",
    transactionNo: "TRX-4041",
    status: "Pending",
    paidAmount: 14000,
  },
  {
    id: 26,
    paymentDate: "2026-03-17",
    deliveryDate: "2026-03-17",
    voucherId: "VOUCH-842",
    doctorId: "DOC-07",
    doctorName: "Dr. Kamrul Islam",
    clinicId: "CLN-07",
    clinicName: "Islami Bank Hospital",
    state: "Rajshahi",
    address: "Laxmipur, Rajshahi",
    caseNo: "CS-9942",
    patientName: "Ayesha Siddiqua",
    paymentMethod: "Bkash",
    transactionNo: "TRX-5051",
    status: "Delivered",
    paidAmount: 23000,
  },
  {
    id: 27,
    paymentDate: "2026-03-18",
    deliveryDate: "2026-03-18",
    voucherId: "VOUCH-843",
    doctorId: "DOC-08",
    doctorName: "Dr. Mizanur Rahman",
    clinicId: "CLN-08",
    clinicName: "Zamzam Hospital",
    state: "Rajshahi",
    address: "Greater Road, Rajshahi",
    caseNo: "CS-9943",
    patientName: "Delowar Hossain",
    paymentMethod: "Bank Transfer",
    transactionNo: "TRX-6061",
    status: "Received",
    paidAmount: 37000,
  },
  {
    id: 28,
    paymentDate: "2026-03-19",
    deliveryDate: "2026-03-19",
    voucherId: "VOUCH-844",
    doctorId: "DOC-09",
    doctorName: "Dr. Asif Mahmud",
    clinicId: "CLN-09",
    clinicName: "Parkview Hospital",
    state: "Chittagong",
    address: "Panchlaish, Chittagong",
    caseNo: "CS-9944",
    patientName: "Mokbul Hossain",
    paymentMethod: "Bkash",
    transactionNo: "TRX-7071",
    status: "Delivered",
    paidAmount: 41000,
  },
  {
    id: 29,
    paymentDate: "2026-03-20",
    deliveryDate: "2026-03-20",
    voucherId: "VOUCH-845",
    doctorId: "DOC-10",
    doctorName: "Dr. Shahriar Alam",
    clinicId: "CLN-10",
    clinicName: "Khulna City Medical",
    state: "Khulna",
    address: "KDA Avenue, Khulna",
    caseNo: "CS-9945",
    patientName: "Salma Khatun",
    paymentMethod: "Nagad",
    transactionNo: "TRX-8081",
    status: "Pending",
    paidAmount: 18500,
  },
  {
    id: 30,
    paymentDate: "2026-03-21",
    deliveryDate: "2026-03-21",
    voucherId: "VOUCH-846",
    doctorId: "DOC-01",
    doctorName: "Dr. Rahim Ahmed",
    clinicId: "CLN-01",
    clinicName: "City Hospital",
    state: "Dhaka",
    address: "House 12, Road 5, Dhanmondi, Dhaka",
    caseNo: "CS-9946",
    patientName: "Riyad Hossain",
    paymentMethod: "Bkash",
    transactionNo: "TRX-9091",
    status: "Delivered",
    paidAmount: 28000,
  },
  {
    id: 31,
    paymentDate: "2026-03-22",
    deliveryDate: "2026-03-22",
    voucherId: "VOUCH-847",
    doctorId: "DOC-02",
    doctorName: "Dr. Sharmin Akter",
    clinicId: "CLN-02",
    clinicName: "Popular Diagnostic",
    state: "Chittagong",
    address: "GEC Circle, Chittagong",
    caseNo: "CS-9947",
    patientName: "Jahangir Alam",
    paymentMethod: "Bank Transfer",
    transactionNo: "TRX-1111",
    status: "Received",
    paidAmount: 60000,
  },
  {
    id: 32,
    paymentDate: "2026-03-23",
    deliveryDate: "2026-03-23",
    voucherId: "VOUCH-848",
    doctorId: "DOC-03",
    doctorName: "Dr. Tanvir Hassan",
    clinicId: "CLN-03",
    clinicName: "Labaid Specialized",
    state: "Dhaka",
    address: "Green Road, Dhanmondi, Dhaka",
    caseNo: "CS-9948",
    patientName: "Nigar Sultana",
    paymentMethod: "Bkash",
    transactionNo: "TRX-2222",
    status: "Delivered",
    paidAmount: 13500,
  },
  {
    id: 33,
    paymentDate: "2026-03-24",
    deliveryDate: "2026-03-24",
    voucherId: "VOUCH-849",
    doctorId: "DOC-04",
    doctorName: "Dr. Farhana Yasmin",
    clinicId: "CLN-04",
    clinicName: "Square Hospital",
    state: "Dhaka",
    address: "Panthapath, Dhaka",
    caseNo: "CS-9949",
    patientName: "Tariqul Islam",
    paymentMethod: "Nagad",
    transactionNo: "TRX-3333",
    status: "Pending",
    paidAmount: 32000,
  },
  {
    id: 34,
    paymentDate: "2026-03-25",
    deliveryDate: "2026-03-25",
    voucherId: "VOUCH-850",
    doctorId: "DOC-05",
    doctorName: "Dr. Mahmudur Rahman",
    clinicId: "CLN-05",
    clinicName: "Ibn Sina Hospital",
    state: "Sylhet",
    address: "Subhanani, Sylhet",
    caseNo: "CS-9950",
    patientName: "Rubel Hossain",
    paymentMethod: "Bkash",
    transactionNo: "TRX-4444",
    status: "Delivered",
    paidAmount: 22500,
  },
  {
    id: 35,
    paymentDate: "2026-03-26",
    deliveryDate: "2026-03-26",
    voucherId: "VOUCH-851",
    doctorId: "DOC-06",
    doctorName: "Dr. Nabila Chowdhury",
    clinicId: "CLN-06",
    clinicName: "Mount Adora Hospital",
    state: "Sylhet",
    address: "Nayasarak, Sylhet",
    caseNo: "CS-9951",
    patientName: "Khadija Begum",
    paymentMethod: "Bank Transfer",
    transactionNo: "TRX-5555",
    status: "Received",
    paidAmount: 47000,
  },
  {
    id: 36,
    paymentDate: "2026-03-27",
    deliveryDate: "2026-03-27",
    voucherId: "VOUCH-852",
    doctorId: "DOC-07",
    doctorName: "Dr. Kamrul Islam",
    clinicId: "CLN-07",
    clinicName: "Islami Bank Hospital",
    state: "Rajshahi",
    address: "Laxmipur, Rajshahi",
    caseNo: "CS-9952",
    patientName: "Babul Mia",
    paymentMethod: "Bkash",
    transactionNo: "TRX-6666",
    status: "Delivered",
    paidAmount: 19000,
  },
  {
    id: 37,
    paymentDate: "2026-03-28",
    deliveryDate: "2026-03-28",
    voucherId: "VOUCH-853",
    doctorId: "DOC-08",
    doctorName: "Dr. Mizanur Rahman",
    clinicId: "CLN-08",
    clinicName: "Zamzam Hospital",
    state: "Rajshahi",
    address: "Greater Road, Rajshahi",
    caseNo: "CS-9953",
    patientName: "Zubaida Khanam",
    paymentMethod: "Nagad",
    transactionNo: "TRX-7777",
    status: "Pending",
    paidAmount: 36000,
  },
  {
    id: 38,
    paymentDate: "2026-03-29",
    deliveryDate: "2026-03-29",
    voucherId: "VOUCH-854",
    doctorId: "DOC-09",
    doctorName: "Dr. Asif Mahmud",
    clinicId: "CLN-09",
    clinicName: "Parkview Hospital",
    state: "Chittagong",
    address: "Panchlaish, Chittagong",
    caseNo: "CS-9954",
    patientName: "Shorif Uddin",
    paymentMethod: "Bkash",
    transactionNo: "TRX-8888",
    status: "Delivered",
    paidAmount: 24000,
  },
  {
    id: 39,
    paymentDate: "2026-03-30",
    deliveryDate: "2026-03-30",
    voucherId: "VOUCH-855",
    doctorId: "DOC-10",
    doctorName: "Dr. Shahriar Alam",
    clinicId: "CLN-10",
    clinicName: "Khulna City Medical",
    state: "Khulna",
    address: "KDA Avenue, Khulna",
    caseNo: "CS-9955",
    patientName: "Tahmina Akter",
    paymentMethod: "Bank Transfer",
    transactionNo: "TRX-9999",
    status: "Received",
    paidAmount: 51000,
  },
  {
    id: 40,
    paymentDate: "2026-03-31",
    deliveryDate: "2026-03-31",
    voucherId: "VOUCH-856",
    doctorId: "DOC-01",
    doctorName: "Dr. Rahim Ahmed",
    clinicId: "CLN-01",
    clinicName: "City Hospital",
    state: "Dhaka",
    address: "House 12, Road 5, Dhanmondi, Dhaka",
    caseNo: "CS-9956",
    patientName: "Jamil Chowdhury",
    paymentMethod: "Bkash",
    transactionNo: "TRX-1234",
    status: "Delivered",
    paidAmount: 17000,
  },
];